# Generated by Django 4.0.6 on 2022-09-18 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_twostepauthmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='twostepauthmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
