# Generated by Django 4.0.6 on 2022-09-19 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_twostepauthmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twostepauthmodel',
            name='userOtp',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
